use EMarket;

/* CREAR FUNCIONES */

DELIMITER $$
CREATE FUNCTION nombreFunction()
RETURNS INT DETERMINISTIC
BEGIN 
  -- INSTRUCCIONES;
  RETURN 
END$$ 
DELIMITER $$;


/* EJEMPLO */
DELIMITER &&
CREATE FUNCTION sayHello()
RETURNS VARCHAR(50) DETERMINISTIC
BEGIN 
	RETURN 'HOLA MARTIN';
END &&
DELIMITER;

/* EJEMPLO 2 */

DELIMITER &&
CREATE FUNCTION humanName(nameHuman VARCHAR(100))
RETURNS VARCHAR(100) DETERMINISTICS
BEGIN 
	RETURN CONCAT("Hola ", nameHuman);
END &&
DELIMITER;

/* llamar a la función */
SELECT sayHello();

/* eliminar funciones */

DROP FUNCTION sayHello;

