/* FECHAS */

SELECT NOW(); /*FECHA ACTUAL*/

SELECT YEAR(NOW()); /*MUESTRA EL AÑO*/
SELECT MONTH(NOW()); /*MUESTRA EL MES*/
SELECT DAY(NOW()); /*MUESTRA EL DIA*/

/*DIFERENCA ENTRE FECHAS*/

SELECT TIMESTAMPDIFF(YEAR, '1978-03-08', NOW());
SELECT TIMESTAMPDIFF(YEAR, '2008-04-07', NOW());
SELECT TIMESTAMPDIFF(YEAR, '2010-06-26', NOW());