use EMarket;

SELECT * FROM CLIENTES;

SELECT SUBSTRING_INDEX(CONTACTO, " ",1) FROM CLIENTES; /*QUIERO HASTA EL PRIMER NOMBRE*/
SELECT UPPER(SUBSTRING_INDEX(CONTACTO, " ", 2)) FROM CLIENTES; /*ME TOMA HASTA EL SEGUNDO ESPACIO Y LOS PONE EN MAYÚSCULAS*/
