/*Funciones numéricas */

use EMarket;

/* NUM ALEATORIOS */

SELECT RAND(); /*ENTRE 0 Y 1 */

/* REDONDEO */
SELECT CEIL(1.2) /*REDONDEO HACIA ARRIBA */;
SELECT FLOOR(3.4) /*REDONDEO PARA ABAJO */;

SELECT ROUND(1.49999) /*REDONDEO AL ENTERO MAS CERCANO */
