import type { Metadata } from "next";
// Corregido: Se importa la fuente Geist desde su propio paquete.
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // Corregido: Se usan las variables de las fuentes GeistSans y GeistMono.
      className={`${GeistSans.variable} ${GeistMono.variable} h-full antialiased`}
    >
      <body >
        <header>
          <nav>
            <div>
                <Link href="/explore">Logo</Link>
            </div>
          </nav>

        </header>
       
        
        
        {children}
      
      
      </body>
    </html>
  );
}
